
spring:
  profiles:
    active: development

---
spring:
  profiles: default

server:
  address: 127.0.0.1
  servlet.context-path: /rail
  email: kphanann@gmail.com


  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8889/railcar?serverTimezone=UTC
    username: railcaradmin
    password: railcaradmin

  jpa:
    hibernate.ddl-auto: update
    generated-ddl: true
    show-sql: true

  security:
    user:
      name: admin
      password: passw0rd
      roles: USER

management:
  endpoints:
    enabled-by-default: true

    web:
      exposure:
        include: "*"

    jmx:
      exposure:
        include: "*"

    endpoints.sensitive: true
    actuator.enabled: true
    autoconfig.enabled: false
    beans.enabled: true
    configprops.enabled: false
    dump.enabled: true
    env.enabled: false
    health.enabled: true
    info.enabled: true
    logfile.enabled: false
    metrics.enabled: true
    mappings.enabled: false
    shutdown.enabled: true
    trace.enabled: false

  endpoint:
    health:
      show-details: ALWAYS

    shutdown:
      enabled: true



endpoints:
  endpoints.sensitive: true
  actuator.enabled: true
  autoconfig.enabled: false
  beans.enabled: true
  configprops.enabled: false
  dump.enabled: true
  env.enabled: false
  health.enabled: true
  info.enabled: true
  logfile.enabled: false
  metrics.enabled: true
  mappings.enabled: false
  shutdown.enabled: true
  trace.enabled: false


liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml

---
spring:
  profiles: development

  security:
    user:
      name: admin
      password: pass
      roles: USER

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:8889/railcar?serverTimezone=UTC
    username: railcaradmin
    password: railcaradmin

server:
  address: 127.0.0.1
  email: kphanann@gmail.com

---
spring:
  profiles: qa

---
spring:
  profiles: production
server:
  address: sodor


#jdbc:mysql://localhost/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
